sonar.projectKey=sentioar-monolithic-ado
sonar.projectName=SentioAR Monolithic Application
sonar.projectVersion=1.0

sonar.sources=frontend/src,backend
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**

sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
sonar.python.coverage.reportPaths=backend/**/coverage.xml

sonar.sourceEncoding=UTF-8
sonar.host.url=http://localhost:9000
